/**
 * Fetch garment photos from the Unsplash API (keyword search) into the catalog
 * photo pool. Far higher hit-rate than guessing photo IDs.
 *
 *   UNSPLASH_ACCESS_KEY=xxx pnpm fetch:photos
 *   UNSPLASH_ACCESS_KEY=xxx pnpm fetch:photos --per 24
 *
 * - Downloads to public/images/catalog/pool/<silhouette>-<n>.jpg
 * - Regenerates src/lib/photo-pool.ts so the catalog picks up the new photos
 * - Then: `pnpm build`
 *
 * Unsplash photos are free to use (Unsplash licence). Demo API keys allow
 * 50 requests/hour — this makes one search request per silhouette (~14 total).
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { EXTRA_POOL as CURRENT } from "../src/lib/photo-pool";

const KEY = process.env.UNSPLASH_ACCESS_KEY;
const POOL_DIR = path.resolve("public/images/catalog/pool");
const POOL_TS = path.resolve("src/lib/photo-pool.ts");

const perArg = process.argv.indexOf("--per");
const PER = Math.min(perArg > -1 ? parseInt(process.argv[perArg + 1], 10) : 30, 30); // Unsplash max 30
const pagesArg = process.argv.indexOf("--pages");
const PAGES = pagesArg > -1 ? parseInt(process.argv[pagesArg + 1], 10) : 3;

// silhouette -> Unsplash search query
const QUERIES: Record<string, string> = {
  tshirt: "folded t-shirt apparel",
  shirt: "dress shirt apparel",
  sweater: "knitted sweater clothing",
  hoodie: "hoodie sweatshirt",
  pants: "trousers jeans apparel",
  widepants: "wide leg trousers",
  shorts: "shorts apparel",
  skirt: "skirt fashion",
  jacket: "jacket apparel",
  coat: "winter coat outerwear",
  cardigan: "cardigan knitwear",
  backpack: "backpack bag",
  handbag: "handbag purse",
  crossbag: "crossbody bag",
};

interface UnsplashPhoto {
  urls: { small: string; regular: string };
}

async function searchPage(query: string, page: number): Promise<UnsplashPhoto[]> {
  const url = `https://api.unsplash.com/search/photos?query=${encodeURIComponent(
    query,
  )}&per_page=${PER}&page=${page}&orientation=portrait&content_filter=high`;
  const res = await fetch(url, { headers: { Authorization: `Client-ID ${KEY}` } });
  if (res.status === 403) throw new Error("rate-limit（403）— 已達 Unsplash 每小時上限，請稍後再試");
  if (!res.ok) throw new Error(`Unsplash ${res.status}: ${await res.text()}`);
  const json = await res.json();
  return (json.results ?? []) as UnsplashPhoto[];
}

/** Fetch up to PAGES pages, de-duplicated by image URL. */
async function search(query: string): Promise<UnsplashPhoto[]> {
  const seen = new Set<string>();
  const out: UnsplashPhoto[] = [];
  for (let page = 1; page <= PAGES; page++) {
    const results = await searchPage(query, page);
    if (results.length === 0) break;
    for (const p of results) {
      if (!seen.has(p.urls.small)) {
        seen.add(p.urls.small);
        out.push(p);
      }
    }
  }
  return out;
}

async function download(srcUrl: string, dest: string): Promise<boolean> {
  try {
    const res = await fetch(srcUrl);
    if (!res.ok) return false;
    await writeFile(dest, Buffer.from(await res.arrayBuffer()));
    return true;
  } catch {
    return false;
  }
}

async function main() {
  if (!KEY) {
    console.error("✗ 缺少 UNSPLASH_ACCESS_KEY。請先 `export UNSPLASH_ACCESS_KEY=...` 再執行。");
    process.exit(1);
  }
  await mkdir(POOL_DIR, { recursive: true });

  // Start from the existing pool so a partial/rate-limited run never loses data.
  const pool: Record<string, string[]> = { ...CURRENT };
  for (const [sil, query] of Object.entries(QUERIES)) {
    process.stdout.write(`搜尋 ${sil} … `);
    let photos: UnsplashPhoto[] = [];
    try {
      photos = await search(query);
    } catch (err) {
      console.error(`失敗（保留現有 ${pool[sil]?.length ?? 0} 張）：${err instanceof Error ? err.message : err}`);
      continue;
    }
    const files: string[] = [];
    let n = 0;
    for (const p of photos) {
      const file = `${sil}-${n}.jpg`;
      if (await download(p.urls.small, path.join(POOL_DIR, file))) {
        files.push(`/images/catalog/pool/${file}`);
        n++;
      }
    }
    pool[sil] = files;
    console.log(`${files.length} 張`);
  }

  const body =
    "// Auto-generated by `pnpm fetch:photos` (scripts/fetch-unsplash.ts).\n" +
    "// Maps a garment silhouette to extra real photos fetched from the Unsplash API.\n" +
    "export const EXTRA_POOL: Record<string, string[]> = " +
    JSON.stringify(pool, null, 2) +
    ";\n";
  await writeFile(POOL_TS, body);

  const total = Object.values(pool).reduce((s, a) => s + a.length, 0);
  console.log(`\n完成：共 ${total} 張，已寫入 ${POOL_TS}。接著執行 \`pnpm build\`。`);
}

main();
