/**
 * Fetch garment photos from the Unsplash API (keyword search) into the catalog
 * photo pool. Far higher hit-rate than guessing photo IDs.
 *
 *   UNSPLASH_ACCESS_KEY=xxx pnpm fetch:photos
 *   UNSPLASH_ACCESS_KEY=xxx pnpm fetch:photos --per 24
 *
 * - Downloads to public/images/catalog/pool/<silhouette>-<n>.jpg
 * - Regenerates src/lib/photo-pool.ts so the catalog picks up the new photos
 * - Then: `pnpm build`
 *
 * Unsplash photos are free to use (Unsplash licence). Demo API keys allow
 * 50 requests/hour — this makes one search request per silhouette (~14 total).
 */
import { mkdir, writeFile, rm } from "node:fs/promises";
import path from "node:path";

const KEY = process.env.UNSPLASH_ACCESS_KEY;
const POOL_DIR = path.resolve("public/images/catalog/pool");
const POOL_TS = path.resolve("src/lib/photo-pool.ts");

const perArg = process.argv.indexOf("--per");
const PER = perArg > -1 ? parseInt(process.argv[perArg + 1], 10) : 24;

// silhouette -> Unsplash search query
const QUERIES: Record<string, string> = {
  tshirt: "folded t-shirt apparel",
  shirt: "dress shirt apparel",
  sweater: "knitted sweater clothing",
  hoodie: "hoodie sweatshirt",
  pants: "trousers jeans apparel",
  widepants: "wide leg trousers",
  shorts: "shorts apparel",
  skirt: "skirt fashion",
  jacket: "jacket apparel",
  coat: "winter coat outerwear",
  cardigan: "cardigan knitwear",
  backpack: "backpack bag",
  handbag: "handbag purse",
  crossbag: "crossbody bag",
};

interface UnsplashPhoto {
  urls: { small: string; regular: string };
}

async function search(query: string): Promise<UnsplashPhoto[]> {
  const url = `https://api.unsplash.com/search/photos?query=${encodeURIComponent(
    query,
  )}&per_page=${PER}&orientation=portrait&content_filter=high`;
  const res = await fetch(url, { headers: { Authorization: `Client-ID ${KEY}` } });
  if (!res.ok) throw new Error(`Unsplash ${res.status}: ${await res.text()}`);
  const json = await res.json();
  return (json.results ?? []) as UnsplashPhoto[];
}

async function download(srcUrl: string, dest: string): Promise<boolean> {
  try {
    const res = await fetch(srcUrl);
    if (!res.ok) return false;
    await writeFile(dest, Buffer.from(await res.arrayBuffer()));
    return true;
  } catch {
    return false;
  }
}

async function main() {
  if (!KEY) {
    console.error("✗ 缺少 UNSPLASH_ACCESS_KEY。請先 `export UNSPLASH_ACCESS_KEY=...` 再執行。");
    process.exit(1);
  }
  await rm(POOL_DIR, { recursive: true, force: true });
  await mkdir(POOL_DIR, { recursive: true });

  const pool: Record<string, string[]> = {};
  for (const [sil, query] of Object.entries(QUERIES)) {
    process.stdout.write(`搜尋 ${sil} … `);
    let photos: UnsplashPhoto[] = [];
    try {
      photos = await search(query);
    } catch (err) {
      console.error(`失敗：${err instanceof Error ? err.message : err}`);
      continue;
    }
    const files: string[] = [];
    let n = 0;
    for (const p of photos) {
      const file = `${sil}-${n}.jpg`;
      if (await download(p.urls.small, path.join(POOL_DIR, file))) {
        files.push(`/images/catalog/pool/${file}`);
        n++;
      }
    }
    pool[sil] = files;
    console.log(`${files.length} 張`);
  }

  const body =
    "// Auto-generated by `pnpm fetch:photos` (scripts/fetch-unsplash.ts).\n" +
    "// Maps a garment silhouette to extra real photos fetched from the Unsplash API.\n" +
    "export const EXTRA_POOL: Record<string, string[]> = " +
    JSON.stringify(pool, null, 2) +
    ";\n";
  await writeFile(POOL_TS, body);

  const total = Object.values(pool).reduce((s, a) => s + a.length, 0);
  console.log(`\n完成：共 ${total} 張，已寫入 ${POOL_TS}。接著執行 \`pnpm build\`。`);
}

main();
